### ISSUE TITLE
WoT 1.18 throws an Exception about "decoding unicode not supported"

### ISSUE THREAD

**Issue by Weltherrscher** [CH4MPi/GUIFlash#9]
Since WoT 1.18.0.0 the game crashes on load if any mod uses gambiter guiflash with the following error message:

"TypeError: decoding Unicode is not supported"

see also the attached log:
[python.log](https://github.com/CH4MPi/GUIFlash/files/9461902/python.log)

**Comment by Weltherrscher** [comment]
Ok, it works with updated plugins, but it also worked with old plugins and guiflash deleted (except no output from these plugins ingame).

**Comment by CH4MPi** [comment]
It's not an issue of guiflash. As you can see in your python.log the problem was the mod_battle_efficiency.
